### ISSUE TITLE
Branding & Connecting back to Blockchain Commons

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/iOS-GordianGuardian#14]
We need to understand mvp here.

**Comment by ChristopherA** [comment]
![Uploading PNG image.png…]()

**Comment by ChristopherA** [comment]
![PNG image](https://user-images.githubusercontent.com/69103/105277959-5e76e800-5b59-11eb-8ffb-edba08e0282d.png)

**Comment by ChristopherA** [comment]
From BlueWallet: 

![PNG image](https://user-images.githubusercontent.com/69103/105278034-88c8a580-5b59-11eb-9c30-a4cce7b4019f.png)

![55D2AC1A-9CAC-4478-9867-3BF6C3DB452B](https://user-images.githubusercontent.com/69103/105278083-a0a02980-5b59-11eb-99de-659c17c0ab7d.png)

**Comment by wolfmcnally** [comment]
I'll look into adding something like this.

**Comment by wolfmcnally** [comment]
@ChristopherA Several of these issues have now been addressed. Please open new tickets with specific issues that need to be addressed for the MVP.
