### ISSUE TITLE
Output Descriptors Need Additional Detail on File Names

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/iOS-GordianGuardian#142]
The output descriptor file names need an additional element describing which output descriptor they are, possibly using the descriptions from #134, possibly the derivation paths, but something so that the files don't overwrite each other.

**Comment by wolfmcnally** [comment]
I don't consider this a bug, but rather an enhancement, and it should be specified more clearly before we implement it. Since we are talking about filenames, we need to be terse and careful about how much information we are including as they are already getting very long!

**Comment by ChristopherA** [comment]
I am very concerned with overwriting of different derivations, especially as many people have both legacy AND segwit accounts on same seed. so we need a solution here.

**Comment by wolfmcnally** [comment]
You could provide a list that includes for each output descriptor variant:

* A descriptive name that can be any length and include spaces
* A short form to be used in export filenames.

**Comment by ChristopherA** [comment]
Assign to @shannona 

Wolf, can you have your audit list updated tonight for him?

**Comment by shannona** [comment]
I think the descriptive names in #134 are a good standard.

Would thus suggest:
|Description|FileName|
|Native Segwit Single Key|segwit|
|Native Segwit Multisig|segwitmultsig|
|Nested Segwit Single Key|nested|
|Nested Segwit Multisig|nestedmultsig|
|Legacy Single Key|legacy|
|Legacy Multisig|legacymultsig|
|Taproot Single Key|taproot|

Any thoughts before we finalize @ChristopherA? The other large possibility is to swap out multisig for cosigner.

**Comment by ChristopherA** [comment]
I think the right answer is to replace key with co-signer, i.e.  “multisig cosigner” not “multisig key”

**Comment by shannona** [comment]
Adjusted per @ChristopherA 

Description|FileName|
|-----|----|
|Native Segwit Single Key|segwit|
|Native Segwit Multisig Cosigner|segwitmultsig|
|Nested Segwit Single Key|nested|
|Nested Segwit Multisig Cosigner|nestedmultsig|
|Legacy Single Key|legacy|
|Legacy Multisig Cosigner|legacymultsig|
|Taproot Single Key|taproot|

**Comment by wolfmcnally** [comment]
Please re-test.

**Comment by shannona** [comment]
These are the outputs:
```
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_legacy_0_frs22d0f]-UR.txt
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_legacymultisig_0_vwnxudyw]-UR.txt
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_nested_0_cmyxclfa]-UR.png
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_nested_0_cmyxclfa]-UR.txt
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_nested_0_cmyxclfa].txt
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_nestedmultisig_0_ycs6cu6j]-UR.txt
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_segwit_0_ncwysjuk]-UR.png
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_segwit_0_ncwysjuk]-UR.txt
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_segwitmultisig_0_wmsu2266]-UR.png
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_segwitmultisig_0_wmsu2266]-UR.txt
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_segwitmultisig_0_wmsu2266].txt
ffa11a8-5db8946-HDKey from Yinmn Blue Acid Exam-Output-[604b93f2_taproot_0_nay7kr6q]-UR.txt
```
Look great.
