### ISSUE TITLE
Settings button / kill switch 

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/iOS-GordianGuardian#16]
We should lock in our UX where the settings button will be.

A key item on here is a kill switch, that deletes the app and data as if you never used it. GW has two, one that starts the app in a new state, the other also kills iCloud data.

Two use cases: testing app, or you no longer wish to use app anymore again but it has critical data to be deleted.

**Comment by wolfmcnally** [comment]
Deleting the app itself deletes all its local data, and we are not currently using iCloud for anything. Why do we need anything else?

**Comment by wolfmcnally** [comment]
We have established a location for global settings now.

**Comment by wolfmcnally** [comment]
OK, does look like we need a Delete All Data button, as the Keychain is *not* cleared upon app deletion:

https://developer.apple.com/forums/thread/22874
