### ISSUE TITLE
Export derived xpub as text+xpub

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/iOS-GordianGuardian#21]
![PNG image](https://user-images.githubusercontent.com/69103/106327976-e2089700-6233-11eb-9d56-3e2e785d52ea.png)

I’ve not seen any wallet that imports a base 64 of this. Instead, some currently support the partial descriptor style, eg [fingerprint/path/to/key/xpub…

We need to be able to export this ASAP as this is what others need to check existing implementations against.

I’d also like press and hold the path in detail to also copy it to clipboard.

**Comment by ChristopherA** [comment]
It may be also with adding in the red detail path view above “/xpub…" as it demonstrates clearly this is an xpub not an xprv. If not, then we need some symbolism to show that this is a safer pubkey derivation rather than the less safe xprv.

**Comment by wolfmcnally** [comment]
We show that this is a public key:
![image](https://user-images.githubusercontent.com/676176/107439124-6f76a180-6ae6-11eb-9585-9317fb434c31.png)

**Comment by wolfmcnally** [comment]
> I’d also like press and hold the path in detail to also copy it to clipboard.

You can already do this.

**Comment by wolfmcnally** [comment]
> I’ve not seen any wallet that imports a base 64 of this. Instead, some currently support the partial descriptor style, eg [fingerprint/path/to/key/xpub…
> 
> We need to be able to export this ASAP as this is what others need to check existing implementations against.

I'm not sure what's being requested here: base64? You mean base58?

**Comment by ChristopherA** [comment]
It only copies the fingerprint & path, not the …, and the base58 only exports the xpub but not the path. I need both together.
