### ISSUE TITLE
CRITICAL: Export Cosigner (48xpub) from GG to GCS fails

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/iOS-GordianGuardian#24]
(same as https://github.com/BlockchainCommons/GordianCosigner-Catalyst/issues/22)

Problem importing Cosigner from GG to CCS:

from GG (8):

![F47950C5-1166-4DF8-B39B-ED59692B0B15](https://user-images.githubusercontent.com/69103/107274511-58ac4e00-6a05-11eb-9a10-f2b08add6a9d.png)
```
ur:crypto-hdkey/oxaxhdclaxptftltaodyihmwoegdhklslffrtywfasstyklendsfeygsntlsbwbnzsiecmjkswaahdcxsaamdygmryaduyfrtecliavsfrfxfwntgrcysavyzcwfnnvlbyghplytenleihlramtaaddyotadlocsdyykaeykaeykaoy
![7F8D0B5D-757F-4160-9697-478D71DCFE81](https://user-images.githubusercontent.com/69103/107275199-48e13980-6a06-11eb-8898-748cf8c178a6.png)
kaocymhaycmmtaxaaaycyadadcsjncycahppf
```

importing in GCS (0.1.12)

![E9FC5DEF-14B3-47B9-A223-BBC8E0109632](https://user-images.githubusercontent.com/69103/107274860-d83a1d00-6a05-11eb-9159-7bcaff7899a9.png)

For testing purpose here is the seed:

![B55004A4-926D-4056-98E7-2E25332B3B45](https://user-images.githubusercontent.com/69103/107274616-7c6f9400-6a05-11eb-9d1b-55c43487c471.png)

```
ur:crypto-seed/oxadgdetrfecmtytaohfprgwrlsgknolctfdjpaosezofptpaasnvyylcysaaxksdegdkpidjziniacxghihjkjycxhfihiajyjljpcxeydyeyehdpdyehcxdegdkpjpjojzihcxglhskokkdtaakskighisinjkcxjkihihiecxhsjtiecxhsjzjzcxjeihkkjkcxioihjtihjphsjyihiecxiyjpjljncxinjycxjkisjlkpjziecxidihcxiajljtjkinieihjpihiecxkpjtjkihiakpjpihcxhsjkcxjyisinjkcxjeihkkcxjnhsjyihjpinhsjzcxinjkcxidihinjtiocxjkishsjpihiecxhsjkcxhscxjyihjkjycxkoihiajyjljpdmfgbezojy
```

**Comment by gorazdko** [comment]
This happens to me to when importing a mainnet key to a Gordian Cosigner which is configured with testnet. The error message should be: "Network does not match!"

**Comment by wolfmcnally** [comment]
As far as I can tell, this is not a bug in Guardian.
